/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul10;

/**
 *
 * @author Lenovo
 */
public class tugas10 extends javax.swing.JFrame {

    /**
     * Creates new form tugas10
     */
    public tugas10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eHasil = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        menProses = new javax.swing.JMenu();
        meltBersih = new javax.swing.JMenuItem();
        menHitung = new javax.swing.JMenu();
        meltPersegi = new javax.swing.JMenuItem();
        meltSegitiga = new javax.swing.JMenuItem();
        meltLingkaran = new javax.swing.JMenuItem();
        menBantuan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data 1");

        jLabel2.setText("Data 2");

        jLabel3.setText("Hasil");

        menFile.setText("File");
        jMenuBar1.add(menFile);

        menProses.setText("Proses");

        meltBersih.setText("Bersih");
        menProses.add(meltBersih);

        menHitung.setText("Hitung");

        meltPersegi.setText("Persegi Panjang");
        meltPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltPersegiActionPerformed(evt);
            }
        });
        menHitung.add(meltPersegi);

        meltSegitiga.setText("Segitiga");
        meltSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltSegitigaActionPerformed(evt);
            }
        });
        menHitung.add(meltSegitiga);

        meltLingkaran.setText("Lingkaran");
        meltLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLingkaranActionPerformed(evt);
            }
        });
        menHitung.add(meltLingkaran);

        menProses.add(menHitung);

        jMenuBar1.add(menProses);

        menBantuan.setText("Bantuan");
        jMenuBar1.add(menBantuan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(eData2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(eData1))
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meltPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltPersegiActionPerformed
 // Menghitung keliling dan luas persegi panjang
    int panjang = Integer.parseInt(eData1.getText());
    int lebar = Integer.parseInt(eData2.getText());
    int keliling = 2 * (panjang + lebar);
    int luas = panjang * lebar;
    eHasil.setText("Keliling: " + keliling + ", Luas: " + luas);
    }//GEN-LAST:event_meltPersegiActionPerformed

    private void meltLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLingkaranActionPerformed
       // Menghitung keliling dan luas lingkaran
    int jariJari = Integer.parseInt(eData1.getText());
    double keliling = 2 * Math.PI * jariJari;
    double luas = Math.PI * jariJari * jariJari;
    eHasil.setText("Keliling: " + keliling + ", Luas: " + luas);
    }//GEN-LAST:event_meltLingkaranActionPerformed

    private void meltSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltSegitigaActionPerformed
       // Menghitung keliling dan luas segitiga
    int alas = Integer.parseInt(eData1.getText());
    int tinggi = Integer.parseInt(eData2.getText());
    int keliling = 3 * alas; // Asumsi segitiga sama sisi
    int luas = (alas * tinggi) / 2;
    eHasil.setText("Keliling: " + keliling + ", Luas: " + luas);
    }//GEN-LAST:event_meltSegitigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eHasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meltBersih;
    private javax.swing.JMenuItem meltLingkaran;
    private javax.swing.JMenuItem meltPersegi;
    private javax.swing.JMenuItem meltSegitiga;
    private javax.swing.JMenu menBantuan;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menHitung;
    private javax.swing.JMenu menProses;
    // End of variables declaration//GEN-END:variables
}
